# Generated by Django 4.0.1 on 2022-03-12 08:47

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_image', models.ImageField(upload_to='blog')),
                ('compressed_image', models.URLField(blank=True, null=True)),
                ('image_type', models.CharField(choices=[('HERO', 'Hero'), ('THUMB', 'Thumbnail'), ('BASIC', 'Basic')], default='BASIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, unique=True)),
                ('tag_name_bn', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('visited_count', models.IntegerField(blank=True, null=True)),
                ('claps_count', models.IntegerField(blank=True, null=True)),
                ('minutes_to_read', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=models.SET(blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogimages')),
                ('tag', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
