# Generated by Django 4.0.1 on 2022-01-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='compressed_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
