# Generated by Django 4.0.1 on 2022-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogimages_compressed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='claps_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='minutes_to_read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='visited_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
