# Generated by Django 4.0.1 on 2022-09-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_author_alter_blogpost_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
