# Generated by Django 4.0.1 on 2023-08-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogimages_created_by_alter_blogimages_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_posts', to='blog.blogimages'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogimages'),
        ),
    ]
