"""
Django settings for salmanwahed_com project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

if Path.exists(BASE_DIR.joinpath(".env")):
    load_dotenv(BASE_DIR.joinpath(".env"))
else:
    raise ImproperlyConfigured(".env file not found.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Path.exists(BASE_DIR.joinpath("credentials.txt")) or os.getenv("DJANGO_DEBUG", "").upper() == "TRUE"

LOG_DIR = BASE_DIR.joinpath("log")
LOG_FILE = "salmanwahed_com.log"

if not Path.exists(LOG_DIR):
    raise ImproperlyConfigured("log directory was not found.")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "{levelname} [{asctime}] [{module} {funcName}:{lineno}] {message}",
            "datefmt": "%d-%b-%Y %I:%M:%S %p",
            "style": "{",
        },
        "simple": {
            "format": "{pathname} {funcName}({lineno}): {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR.joinpath(LOG_FILE),
            "formatter": "default",
            "level": "INFO",
        },
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["require_debug_true"],
            "formatter": "simple",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "default": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

ALLOWED_HOSTS = [".salmanwahed.com"]
if DEBUG:
    ALLOWED_HOSTS.extend(["127.0.0.1", "localhost"])
else:
    ALLOWED_HOSTS.append(os.getenv("SERVER_IP"))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "blog",
    "portfolio",
    "compressor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "salmanwahed_com.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.joinpath("templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "salmanwahed_com.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379"),
        # redis-py 6 and later negotiate RESP3 by default, which opens every
        # connection with a HELLO command. HELLO arrived in Redis 6.0, so
        # against the Redis 5.0 that Ubuntu 20.04 ships, every cached view
        # raises ResponseError and the site answers 500. RESP2 is understood by
        # every Redis version and the cache backend uses no RESP3 feature, so
        # pinning it costs nothing. Removable once the server runs Redis 6+.
        "OPTIONS": {"protocol": 2},
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR.joinpath("static")

# Shared assets used by both apps (tokens, fonts, theme toggle). Kept out of
# STATIC_ROOT, which is collectstatic's output directory.
STATICFILES_DIRS = [BASE_DIR.joinpath("assets")]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Opt in early to Django 6.0's URLField behaviour: a bare domain typed into an
# admin form resolves to https rather than http. Every URL this site stores is
# https already, and setting it now silences the transitional warning.
FORMS_URLFIELD_ASSUME_HTTPS = True

INTERNAL_IPS = [
    "0.0.0.0",
    "127.0.0.1",
]

MEDIA_URL = "/upload/"
MEDIA_ROOT = BASE_DIR.joinpath("upload")

PAGINATION_ITEM_COUNT = 5

CDN_URL = os.getenv("CDN_URL")
USE_CDN = os.getenv("USE_CDN", "FALSE").upper() == "TRUE"
WPM_READ = int(os.getenv("WPM_READ", 180))

#  Django compressor
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

COMPRESS_ENABLED = True

# Contact form email. Mail lands in the console during development so no
# credentials are needed to exercise the form locally.
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "hello@salmanwahed.com")
CONTACT_RATE_LIMIT = int(os.getenv("CONTACT_RATE_LIMIT", 5))  # submissions per IP per hour

# The contact page shows a mailto link only until outbound SMTP is configured.
# With no working relay the form can accept a message and then fail to deliver
# it, which loses the enquiry silently -- a plain mailto cannot. Set to TRUE to
# bring the form back once sending is verified.
CONTACT_FORM_ENABLED = os.getenv("CONTACT_FORM_ENABLED", "FALSE").upper() == "TRUE"

# Console in development, SMTP in production. EMAIL_BACKEND overrides the
# choice, which is the only way to exercise a real send locally: DEBUG cannot
# simply be switched off to test mail, because that also drops 127.0.0.1 from
# ALLOWED_HOSTS and every request starts 400ing.
_default_backend = (
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", _default_backend)

# Read unconditionally. They were previously set only on the production branch,
# so a local SMTP test silently fell back to Django's localhost:25 defaults.
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "TRUE").upper() == "TRUE"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", CONTACT_EMAIL)

# Sentry SDK
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

if not DEBUG:
    sentry_sdk.init(
        dsn=os.getenv("SENTRY_DSN"),
        integrations=[DjangoIntegration()],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=1.0,
        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True,
    )
