# Generated by Django 4.0.1 on 2022-06-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='File Name')),
                ('orig_image', models.ImageField(upload_to='portfolio')),
                ('compressed_image', models.URLField(blank=True, null=True)),
                ('image_type', models.CharField(choices=[('BANNER', 'Banner'), ('THUMB', 'Thumbnail'), ('BASIC', 'Basic')], default='BASIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, unique=True)),
                ('color_code', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Project URL')),
                ('project_type', models.CharField(choices=[('MOBILE_APP', 'Mobile Application'), ('WEB_APP', '')], default='MOBILE_APP', max_length=20, verbose_name='Project Type')),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('ONGOING', 'Ongoing'), ('CLOSED', 'Closed')], default='LIVE', max_length=20)),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('utm_url', models.URLField(blank=True, null=True, verbose_name='UTM Url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='portfolio.projectimage')),
                ('tag', models.ManyToManyField(to='portfolio.Tag')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='portfolio.projectimage')),
            ],
        ),
    ]
