# Generated by Django 4.0.1 on 2023-08-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tag_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_projects', to='portfolio.projectimage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(related_name='projects', to='portfolio.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectimage'),
        ),
    ]
