# Generated by Django 4.2.30 on 2026-08-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_appprivacypolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[("PROFESSIONAL", "Professional work"), ("PERSONAL", "Open source & personal app")],
                db_index=True,
                default="PERSONAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False, help_text='Shows the "Featured" badge.'),
        ),
        migrations.AddField(
            model_name="project",
            name="period",
            field=models.CharField(blank=True, help_text="e.g. 2019 — Present", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(blank=True, help_text="e.g. Senior Software Engineer", max_length=100),
        ),
        migrations.CreateModel(
            name="ProjectStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text="e.g. Users", max_length=40)),
                ("value", models.CharField(help_text="e.g. 8M+", max_length=20)),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="portfolio.project"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
