# Generated by Django 4.2.30 on 2026-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_rename_project_meta_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[("PROFESSIONAL", "Professional work"), ("PERSONAL", "Personal Works")],
                db_index=True,
                default="PERSONAL",
                max_length=20,
            ),
        ),
    ]
